### PR TITLE
Monorepo

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

- Converts the project to a monorepo, using yarn's [workspaces](https://yarnpkg.com/lang/en/docs/workspaces/).
- Reconsiders the roles of the current code. 

_While the repo is still called `guui`, it might be better thought of as – and maybe renamed to – `dotcom-rendering` or suchlike, if this PR is merged._

### `/packages`

It creates 3 separate new (to this context, anyway) packages:

- `/guui` a set of guardian-styled components and helpers
- `/pasteup` a collection of guardian design tokens
- `/rendering` generic entry points for bespoke browser and server bundles

While these versions are not currently published for reuse outside this repo, `guui` and `pasteup` are intended to be.

### `/sites`

It also adds the notion of `sites` to the top level. This folder is somewhat analogous to the current `pages` directory (to create a new site, you add folder to `sites`), and to some extent, the 'applications' in frontend.  

Currently, this only contains `dotcom`, which would contain all the code specific to rendering the main website. 

In reality we may never actually add another site in here. However, @SiAdcock @GHaberis and I discussed this IRL, and felt it helped clarify exactly what code you were adding/editing/deleting, wrt to whether it's actually part of `pasteup`, `guui` or site-specific. 

If we do want to move other sites in here in the future (especially things platform looks after, like email templates etc), it _should_ be fairly trivial, although it's not the point of this PR and may not be as simple as that (and I've obvs jinxed that now anyway).

### Other changes

- The repo has been generally flattened out. Config files have been pulled to the top, and out of `package.json`, in the hope this makes things more discoverable (at the cost of some visual noise).
- Helper directories have been reduced, and the `__JEST__`-style directory names removed. It felt like it became to easy to create new ones – adding more noise – if you could add things for 'free' (i.e. just mark them as non-source code). 
- Config-type code, for example the list of pillars in the nav, has been pulled out of the app state, since it's immutable, in reality, and doesn't need to respond to updates.

## Reviewing

This is a lot of change, and reviewing might be impossible on github. It might be easier to look over [check the entire branch](https://github.com/guardian/guui/tree/mono-repo) for confusing changes and unclear structure etc.

We can go through it IRL next week too, if we have time (at some point, anyway). Hope people find this useful!

## Todo
- [ ] go through the riffraff/publishing stuff with people better acquainted with it than me – I havn't looked at that yet

### CODE REVIEW

**Comment by SiAdcock** [comment]
I really love this change in a lot of ways. The boundaries are clear. The directory structure is sensible and intuitive. The Universal JS bundling is abstracted away. If a site has different opinions about the structure, linting or Flow, then it encourages the maintainers to keep it out of here, and instead include `guui` and `pasteup` as external dependencies in their own repo. In this way, `dotcom-rendering` can be opinionated but still offer an escape hatch to a more flexible way of doing things.

The only thing I noticed was that the README needs updating (would be good to document `make start site=xyz`)

Fantastic work 👏

**Comment by SiAdcock** [comment]
Quick q: is it possible to run the application locally in PROD mode? When I run `make start site=dotcom` and hit `http://localhost:9000` it looks like the requests for JS assets are pointing at the remote assets server

screen shot 2018-05-01 at 16 33 06

**Comment by nicl** [comment]
This looks great. A question I have is how do we avoid a situation like `common` in the Scala codebase?

I.e. a lot of shared code between various pages/components under the sites directory?

It might be worth having a rule like:

* no shared code between components that doesn't like in pastup or guui

and then some way to fail builds if they break this.

If this feels too draconian on the component level, you could apply it to groupings like 'article', 'onward' etc. - i.e. a bit like the way the current scala apps are separated. Although I think this is also a recipe for trouble.

The outcome worth avoiding is where to update one component you suddenly find you need to update many. Avoiding shared code is one way.

A logical extension of avoiding shared code is to support multiple versions of a component. This has big pros and cons.

Pros:

* completely decouples things meaning you can ignore old stuff while changing new things

Cons:

* visual inconsistency across site
* possibly leads to code bloat as less incentive to tidy up old stuff

There are two ways to support multiple versions of a component:

1) simply give new versions a different name (e.g. widget-v1,v2,..)
2) publish versioned artifacts using e.g. npm and then splitting sites into multiple apps, e.g. for article, onward, etc. and allowing each to have different versions

I think 1) is a good patter and something we should actively embrace.

**Comment by sndrs** [comment]
yeah i agree the presence of a `common` directory is a code smell i think, esp here. 

i went with `pages` and `sites` here (borrowing from next.js's `pages`) as a way of trying to break things up visually, rather than conceptually. so we could end up with something like:

```
sites
  dotcom
    components
      footer
      header
        logo
        nav
      most-read
      rich-link
    pages
      article
      article-immersive
      article-longread
      front
  email
    components
      footer
      nav
    pages
      today
```
i would be super-inclined to lint against importing any component from another `site`, and from another `page` within a `site` though. 

you could argue that `components` is a kind of `common` directory, though. do you think it could suffer a similar fate?

**Comment by GHaberis** [comment]
I haven't had a chance to review the entire contents of this PR. But I'm going to throw up a use case for some 'common' code which might be needed across components/pages (and potentially sites). 

Imagine we have some code that enhances embedded tweets. Embedded tweets might exist in a `Body` component on an `Article` page or a `Block` component on a `Liveblog` page. Do we duplicate this code across `Article` and `Liveblog` or move it to a single common location from where it can be imported. Let's just imagine this code is only specific to the `dotcom` site for now. Would we have a `dotcom/utils` folder from which it's OK to import? 

I'd say linting against components importing components from other `sites`, or subcomponents from other `components` seems appropriate.

**Comment by sndrs** [comment]
in that instance, i think we'd have a `components/tweet` component that discreetly enhanced the tweet it embedded?

**Comment by GHaberis** [comment]
Tweets are embedded in the html from CAPI that we dangerously set so I'm not quite sure how that translates to a component that sits in the component-tree.

**Comment by GHaberis** [comment]
Ok yes totally agree the `tweet` scenario needs further discussion, we should do that off this thread.

So another example which doesn't involve modifying HTML, would be an equivalent of `storage.js`, a module in `frontend` used for reading writing to `localStorage`.

Thinking about it, could something like this be made available by `guui` perhaps? eg. `guui/utils`, seems like this would be useful across `sites`/`pages`/`components`.

**Comment by SiAdcock** [comment]
A couple of potentially useful articles

- https://blog.hichroma.com/hidden-in-plain-site-the-levels-of-component-reuse-ee9b0d7b1bd2
- https://dmitripavlutin.com/7-architectural-attributes-of-a-reliable-react-component

**Comment by sndrs** [comment]
in the case of `storage`, that feels like it might be more of a `site`-specific thing? if we want to create a reusable lib of helpers like this, maybe we could create a whole new package? that feels like it's less of a component-thing, but it might be useful to have a known set of well tested utilities? even if they just wrapped 3rd parties?

**Comment by nicl** [comment]
Re storage under /utils agree with @sndrs that it is worth separating out re-usable components from site-specific behaviour. I'd also avoid utils as a name, as while it is great on small projects, it can induce bad behaviour on larger ones 😬 .

But backing up, the main reason `common` is bad in Dotcom is that it couples the apps. Something like storage (which presumably just indirects over local storage) is probably justified, but you want to keep the shared logic very minimal as this is the code that makes things hard to change in the future. DRY is less important than decoupling in a lot of cases for larger code bases (which are really multiple apps, even if in the same monorepo, and may even be deployed separately in future - my hope!).

**Pull request merged**
