### PR TITLE
Mono deploy

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?

updates deploy scripts for monorepo

1. moves deploy-specific scripts to `deploy` dir
2. updates static copy task to copy all `sites/[site]/static/**/*` to `frontend-static'/guui'/static/[site]/`

## Why?

get nearer to deploys working.

## todo
- [x] check how to refs assets from inside sites in dev and prod
- [x] make sure frontend points to the right URL now

### CODE REVIEW

**Comment by MatthewJWalls** [comment]
fyi if you want to test this you should be able to use riffraff to deploy this branch of guui to code, and then look inside the s3 bucket ```aws-frontend-static/CODE/frontend-static/guui``` and see if the appropriate assets have been laid out there from the bundle. 

Our static assets url ```//assets.guim.co.uk/guui``` points directly to this s3 bucket.

**Comment by MatthewJWalls** [comment]
I pushed a commit to fix the make start command. It deploys fine now. Code seems to work, I tried ?guui on m.code and it's showing the right thing.

I don't think the javascript filenames are being hashed anymore. We get vendor.js instead of vendor.vendor.75b855d58dadae49c8c2.js and so on.

**Comment by sndrs** [comment]
@MatthewJWalls 👍

**Comment by sndrs** [comment]
ok, i believe this is good to go once #87 is merged! do your worst...

**Pull request merged**
