### PR TITLE
Consolidate 404 page

### PR DESCRIPTION
**Pull request by sndrs**
## What does this change?
moves 404 page assets to `pages/NotFound`, since it's all bespoke to that page
## Why?
looking at dir structure for adding the epic. it seems to align with a rule that components should be for reused things?

### CODE REVIEW

**Comment by GHaberis** [comment]
Agreed that it makes sense to move `components/NotFound` into `pages/NotFound`.

 If a page's JS file becomes unruly would it make sense to follow a pattern like: `pages/NotFound/index.js` and components sitting in their own directory `pages/NotFound/components/MyComponent.js`?

**Comment by sndrs** [comment]
i wonder if will confusing seeing `components/x` and `./components/y`? are they a bit similar?

**Comment by GHaberis** [comment]
I guess that's a bridge we can cross when we come to it!

**Comment by GHaberis** [comment]
Oh I see, if a `page` uses components from the main shared `Components` directory or it's own `Components` directory. Yeah it could be confusing. Perhaps you could have `pages/NotFound/index.js` and components sitting as sublings eg. `pages/NotFound/MyComponent.js`/`pages/NotFound/MyComponent/index.js`...

**Comment by sndrs** [comment]
is that not what this does?

**Comment by sndrs** [comment]
although not all of them it's true

**Comment by GHaberis** [comment]
OK yes that's exactly what this does! A`NotFound` directory within which we have `index.js` `BackToGuardianButton.js` and `notfound.svg`...this is what i'd suggested above ☝️

**Pull request merged**
